### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by szepeviktor** [joskolenberg/jory#13]
Could you talk about security in the README?

**Comment by joskolenberg** [comment]
Hello @szepeviktor,

Sorry I missed your message, but thanks for the input.

There is no mentions at the Jory docs of security because that's really up to the implementation.

I just released a new release for my Laravel implementation which now has a chapter on security in the readme: https://github.com/joskolenberg/laravel-jory#security

**Comment by szepeviktor** [comment]
Thank you.
